language: node_js
node_js:      
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
script:
      - npm run lint
      - npm test
      - npm run test:cov      
      - npm run compile

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js